#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import sys
sys.path.insert(0, '.')
from docx_helper import create_document, add_cover, add_heading1, add_heading2, add_heading3, add_para, add_bullet, add_table, save_doc

doc = create_document('数据库设计文档')

add_cover(doc, '数据库设计文档', '华电新能源测点编码管理平台', 'V1.1', '2026-06-08')
add_heading1(doc, '目录')
add_para(doc, '(生成后请在 Word 中右键点击此处 -> 更新域 -> 更新整个目录)')
doc.add_page_break()
add_heading1(doc, '1. 设计概述')
add_heading2(doc, '1.1 设计范围')
add_para(doc, '本文档涵盖了华电新能源测点编码管理平台核心业务模块的数据库表结构设计，包括字典管理模块、编码生成模块、编码校验与修正模块、用户与权限管理模块、审批流程模块、场站管理模块以及时序规则分析模块。')
add_heading2(doc, '1.2 设计原则')
add_para(doc, '本平台数据库设计遵循以下核心原则：')
add_bullet(doc, '规范化设计：遵循第三范式进行表结构设计，减少数据冗余，确保数据一致性。')
add_bullet(doc, '逻辑删除：所有业务表均采用逻辑删除策略，通过 if_delete 字段标识数据状态（0正常，1删除）。')
add_bullet(doc, '无外键约束：不设置物理外键约束，数据完整性和一致性由应用层 Java 代码保证。')
add_bullet(doc, 'Schema级多租户隔离：采用 PostgreSQL Schema 机制实现多租户数据隔离。')
add_heading2(doc, '1.3 命名规范')
add_para(doc, '数据库对象命名遵循以下统一规范：')
add_bullet(doc, '表名使用小写字母和下划线命名法（snake_case），如 cec_new_energy_code_dict。')
add_bullet(doc, '业务表统一使用前缀 cec_new_energy_*，系统管理表使用前缀 cec_sys_*，时序规则表使用前缀 tsr_*。')
add_bullet(doc, '审计字段统一命名为 tenant_id、creator、modifier、create_tm、modify_tm、if_delete。')
add_bullet(doc, '所有业务表的主键统一使用 BIGSERIAL 自增类型。')
print('Section 1 done')
add_heading1(doc, '2. 多租户数据隔离方案')
add_heading2(doc, '2.1 数据库级+Schema级双重隔离')
add_para(doc, '平台采用数据库级+Schema级双重隔离方案。集团管理员（admin）连接远程数据库（10.1.1.113:7300/training_exercises），区域租户（yunnan/fujian）连接本地数据库（localhost/code_tools）。同一数据库内通过 Schema 实现逻辑隔离，不同数据库实例之间实现物理隔离。')
add_table(doc, ["租户名称", "租户标识", "数据库连接", "Schema名称"], [["admin", "集团管理员", "10.1.1.113:7300/training_exercises", "liuhaojun"], ["yunnan", "云南区域租户", "localhost/code_tools", "yunnan"], ["fujian", "福建区域租户", "localhost/code_tools", "fujian"]], col_widths=[3, 3, 6, 4])
add_heading2(doc, '2.2 隔离策略')
add_para(doc, '不同类型的数据采用不同的隔离策略。默认连接池配置持久化于config/datasource.json文件，支持运行时热切换：')
add_table(doc, ["数据类型", "隔离策略", "说明"], [["字典数据", "数据库+Schema隔离", "admin在远程库liuhaojun Schema，区域在本地库各自Schema"], ["编码记录", "数据库+Schema隔离", "编码记录存储在各自数据库的Schema中"], ["用户数据", "仅admin库", "cec_sys_user表仅存于admin远程库liuhaojun Schema"], ["审批数据", "仅admin库", "审批数据统一存储在admin远程库"]], col_widths=[3, 3, 10])
add_heading2(doc, '2.3 Schema设计特点')
add_bullet(doc, 'admin（集团）租户连接远程数据库（10.1.1.113:7300/training_exercises/liuhaojun Schema）。')
add_bullet(doc, '区域租户连接本地数据库（localhost/code_tools/各自 Schema）。')
add_bullet(doc, '区域租户字典新增/修改提审后同步至 admin 远程库审批表。')
add_bullet(doc, '默认连接池通过config/datasource.json配置，支持运行时热切换无需重启服务。')
print('Section 2 done')
add_heading1(doc, '3. 核心表设计')
add_para(doc, '核心表按业务功能划分为字典相关表、编码业务表、校验与修正表、用户与权限表、审批相关表、场站表、时序规则表等七大类。')
add_heading2(doc, '3.1 字典相关表')
add_heading3(doc, '3.1.1 类型域字典表（cec_new_energy_type_dict）')
add_para(doc, '定义编码的最高层级分类，即能源类型。支持风电（F）、光伏（G）、水电（Y）三种。')
add_table(doc, ["字段名", "类型", "说明"], [["type_id", "BIGSERIAL", "主键，自增"], ["type_code", "VARCHAR(2)", "类型域编码 F/G/Y"], ["type_name", "VARCHAR(100)", "类型域名称"]], col_widths=[3, 4, 10])
add_heading3(doc, '3.1.2 编码字典表（cec_new_energy_code_dict）')
add_para(doc, '平台核心字典表，定义五级分类：类型域 -> 一级类码 -> 二级类码 -> 数据分类码 -> 数据码。')
add_table(doc, ["字段名", "类型", "说明"], [["code_dict_id", "BIGSERIAL", "主键，自增"], ["type_domain_code", "CHAR(1)", "类型域 CHECK(F/G/Y)"], ["first_class_code", "VARCHAR(2)", "一级类码"], ["first_class_name", "VARCHAR(100)", "一级类名称"], ["second_class_code", "VARCHAR(3)", "二级类码"], ["second_class_name", "VARCHAR(100)", "二级类名称"], ["data_category_code", "VARCHAR(2)", "数据分类码"], ["data_category_name", "VARCHAR(100)", "数据分类名称"], ["data_code", "VARCHAR(3)", "数据码"], ["data_name", "VARCHAR(100)", "数据名称"], ["is_manual", "CHAR(1)", "是否手动录入 Default 0"], ["type_code", "VARCHAR(10)", "冗余类型域编码"]], col_widths=[3, 5, 9])
add_heading3(doc, '3.1.3 二级类码字典表（cec_new_energy_second_class_type_dict）')
add_table(doc, ["字段名", "类型", "说明"], [["id", "BIGSERIAL", "主键，自增"], ["type_code", "VARCHAR(2)", "类型域编码"], ["second_class_code", "VARCHAR(3)", "二级类码"], ["second_class_name", "VARCHAR(100)", "二级类名称"]], col_widths=[3, 4, 10])
add_heading3(doc, '3.1.4 三级类码字典表（cec_new_energy_third_class_dict）')
add_table(doc, ["字段名", "类型", "说明"], [["id", "BIGSERIAL", "主键，自增"], ["type_code", "VARCHAR(2)", "类型域编码"], ["second_class_code", "VARCHAR(3)", "二级类码"], ["third_class_code", "VARCHAR(3)", "三级类码"], ["third_class_name", "VARCHAR(100)", "三级类名称"]], col_widths=[3, 4, 10])
add_heading3(doc, '3.1.5 编码前缀字典表与项目线字典表')
add_para(doc, '前缀字典表（cec_new_energy_prefix_dict）和项目线字典表（cec_new_energy_project_line_dict）管理编码前缀和项目期号。')
add_table(doc, ["字段名", "类型", "说明"], [["id", "BIGSERIAL", "主键，自增"], ["code", "VARCHAR(10)", "编码"], ["name", "VARCHAR(100)", "名称"]], col_widths=[3, 4, 10])
print('Section 3.1 done')
add_heading2(doc, '3.2 编码业务表')
add_heading3(doc, '3.2.1 编码生成记录表（cec_new_energy_createcode）')
add_table(doc, ["字段名", "类型", "说明"], [["id", "BIGSERIAL", "主键，自增"], ["code", "VARCHAR(31)", "31位编码"], ["name", "VARCHAR(500)", "编码名称"], ["batch_no", "VARCHAR(20)", "批次号"], ["type_code", "VARCHAR(10)", "类型域编码"], ["second_class_code", "VARCHAR(3)", "二级类码"], ["data_type_code", "VARCHAR(10)", "数据类型编码"], ["station_code", "VARCHAR(10)", "场站编码"], ["third_class_code", "VARCHAR(3)", "三级类码"], ["tenant_id", "VARCHAR(50)", "租户ID"], ["creator", "VARCHAR(100)", "创建人"], ["modifier", "VARCHAR(100)", "修改人"], ["create_tm", "TIMESTAMP", "创建时间"], ["modify_tm", "TIMESTAMP", "修改时间"], ["if_delete", "CHAR(1)", "逻辑删除"]], col_widths=[3, 5, 9])
add_heading3(doc, '3.2.2 最近筛选条件表（cec_new_energy_recent_condition）')
add_table(doc, ["字段名", "类型", "说明"], [["id", "BIGSERIAL", "主键，自增"], ["condition_data", "JSONB", "筛选条件 JSON"], ["condition_summary", "VARCHAR(500)", "条件摘要"], ["tenant_id", "VARCHAR(50)", "租户ID"], ["creator", "VARCHAR(100)", "创建人"], ["create_tm", "TIMESTAMP", "创建时间"], ["if_delete", "CHAR(1)", "逻辑删除"]], col_widths=[3, 5, 9])
add_heading3(doc, '3.2.3 全量测点数据表（cec_new_energy_measurement_points）')
add_table(doc, ["字段名", "类型", "说明"], [["id", "BIGSERIAL", "主键，自增"], ["code", "VARCHAR(31)", "31位测点编码"], ["station_code", "VARCHAR(4)", "场站编码 1-4位"], ["type_code", "VARCHAR(2)", "类型域 第5位"], ["project_line_code", "VARCHAR(3)", "项目期号 6-8位"], ["prefix_no", "VARCHAR(1)", "前缀号 第9位"], ["first_class_code", "VARCHAR(2)", "一级类码 10-11位"], ["second_class_code", "VARCHAR(3)", "二级类码 12-14位"], ["second_ext_code", "VARCHAR(4)", "二级扩展码 15-18位"], ["third_class_code", "VARCHAR(3)", "三级类码 19-21位"], ["third_ext_code", "VARCHAR(4)", "三级扩展码 22-25位"], ["data_category_code", "VARCHAR(2)", "数据分类码 26-27位"], ["data_code", "VARCHAR(3)", "数据码 29-31位"], ["import_batch_id", "VARCHAR(50)", "导入批次ID"], ["tenant_id", "VARCHAR(50)", "租户ID"], ["creator", "VARCHAR(100)", "创建人"], ["modifier", "VARCHAR(100)", "修改人"], ["create_tm", "TIMESTAMP", "创建时间"], ["modify_tm", "TIMESTAMP", "修改时间"], ["if_delete", "CHAR(1)", "逻辑删除"]], col_widths=[3, 5, 9])
print('Section 3.2 done')
add_heading2(doc, '3.3 校验与修正表')
add_heading3(doc, '3.3.1 编码稽核数据表（cec_new_energy_checkdata）')
add_table(doc, ["字段名", "类型", "说明"], [["id", "BIGSERIAL", "主键，自增"], ["check_batch", "VARCHAR(50)", "稽核批次号"], ["original_code", "VARCHAR(31)", "原始编码"], ["check_result", "VARCHAR(20)", "PASS/FAIL"], ["check_notes", "TEXT", "异常描述"], ["tenant_id", "VARCHAR(50)", "租户ID"], ["creator", "VARCHAR(100)", "创建人"], ["create_tm", "TIMESTAMP", "创建时间"], ["modifier", "VARCHAR(100)", "修改人"], ["modify_tm", "TIMESTAMP", "修改时间"], ["if_delete", "CHAR(1)", "逻辑删除"]], col_widths=[3, 5, 9])
add_heading3(doc, '3.3.2 编码修正记录表（cec_new_energy_code_correction）')
add_para(doc, '应用层动态创建。')
add_table(doc, ["字段名", "类型", "说明"], [["id", "BIGSERIAL", "主键，自增"], ["correction_batch", "VARCHAR(50)", "修正批次号"], ["original_code", "VARCHAR(31)", "修正前编码"], ["corrected_code", "VARCHAR(31)", "修正后编码"], ["correction_reason", "TEXT", "修正原因"], ["tenant_id", "VARCHAR(50)", "租户ID"], ["creator", "VARCHAR(100)", "创建人"], ["create_tm", "TIMESTAMP", "创建时间"], ["if_delete", "CHAR(1)", "逻辑删除"]], col_widths=[3, 5, 9])
add_heading3(doc, '3.3.3 编码映射表（cec_new_energy_code_mapping）')
add_para(doc, '应用层动态创建。新旧编码映射关系。')
add_table(doc, ["字段名", "类型", "说明"], [["id", "BIGSERIAL", "主键，自增"], ["old_code", "VARCHAR(31)", "旧编码"], ["new_code", "VARCHAR(31)", "新编码"], ["mapping_type", "VARCHAR(20)", "映射类型"], ["tenant_id", "VARCHAR(50)", "租户ID"], ["creator", "VARCHAR(100)", "创建人"], ["create_tm", "TIMESTAMP", "创建时间"], ["if_delete", "CHAR(1)", "逻辑删除"]], col_widths=[3, 5, 9])
print('Section 3.3 done')
add_heading2(doc, '3.4 用户与权限表')
add_heading3(doc, '3.4.1 系统用户表（cec_sys_user）')
add_para(doc, '仅 admin Schema。预置 admin/yunnan/fujian。')
add_table(doc, ["字段名", "类型", "说明"], [["id", "BIGSERIAL", "主键，自增"], ["username", "VARCHAR(100)", "用户名 UNIQUE"], ["display_name", "VARCHAR(200)", "显示名称"], ["region", "VARCHAR(200)", "区域"], ["tenant", "VARCHAR(100)", "租户标识"], ["password", "VARCHAR(200)", "密码加密"], ["last_login_time", "TIMESTAMP", "最后登录"], ["create_tm", "TIMESTAMP", "创建时间"], ["update_tm", "TIMESTAMP", "更新时间"]], col_widths=[3, 5, 9])
print('Section 3.4 done')
add_heading2(doc, '3.5 审批相关表')
add_heading3(doc, '3.5.1 字典审批记录表（cec_new_energy_code_approval）')
add_para(doc, '仅 admin Schema。状态：pending/approved/rejected。')
add_table(doc, ["字段名", "类型", "说明"], [["approval_id", "BIGSERIAL", "主键，自增"], ["source_tenant", "VARCHAR(50)", "来源租户"], ["type_code", "VARCHAR(10)", "类型域编码"], ["second_class_code", "VARCHAR(3)", "二级类码"], ["second_class_name", "VARCHAR(100)", "二级类名称"], ["data_category_code", "VARCHAR(2)", "数据分类码"], ["data_category_name", "VARCHAR(100)", "数据分类名称"], ["data_code", "VARCHAR(3)", "数据码"], ["data_name", "VARCHAR(100)", "数据名称"], ["status", "VARCHAR(20)", "审批状态"], ["reject_reason", "TEXT", "驳回原因"], ["submitter", "VARCHAR(50)", "提交人"], ["reviewer", "VARCHAR(50)", "审批人"], ["submit_tm", "TIMESTAMP", "提交时间"], ["review_tm", "TIMESTAMP", "审批时间"]], col_widths=[3, 5, 9])
add_heading3(doc, '3.5.2 字典新增草稿表（cec_new_energy_code_draft）')
add_para(doc, '租户本地 Schema。提审后同步至 admin Schema。')
add_table(doc, ["字段名", "类型", "说明"], [["draft_id", "BIGSERIAL", "主键，自增"], ["type_code", "VARCHAR(10)", "类型域编码"], ["second_class_code", "VARCHAR(3)", "二级类码"], ["second_class_name", "VARCHAR(100)", "二级类名称"], ["data_category_code", "VARCHAR(2)", "数据分类码"], ["data_category_name", "VARCHAR(100)", "数据分类名称"], ["data_code", "VARCHAR(3)", "数据码"], ["data_name", "VARCHAR(100)", "数据名称"], ["status", "VARCHAR(20)", "草稿状态"], ["reject_reason", "TEXT", "驳回原因"], ["approval_id", "BIGINT", "关联审批ID"], ["creator", "VARCHAR(100)", "创建人"], ["create_tm", "TIMESTAMP", "创建时间"], ["modifier", "VARCHAR(100)", "修改人"], ["modify_tm", "TIMESTAMP", "修改时间"]], col_widths=[3, 5, 9])
print('Section 3.5 done')
add_heading2(doc, '3.6 场站表')
add_heading3(doc, '3.6.1 场站字典表（cec_new_energy_station_dict）')
add_table(doc, ["字段名", "类型", "说明"], [["id", "BIGSERIAL", "主键，自增"], ["station_code", "VARCHAR(4)", "场站编码"], ["station_name", "VARCHAR(100)", "场站名称"], ["region", "VARCHAR(50)", "区域"], ["tenant_id", "VARCHAR(50)", "租户ID"], ["creator", "VARCHAR(100)", "创建人"], ["modifier", "VARCHAR(100)", "修改人"], ["create_tm", "TIMESTAMP", "创建时间"], ["modify_tm", "TIMESTAMP", "修改时间"], ["if_delete", "CHAR(1)", "逻辑删除"]], col_widths=[3, 5, 9])
print('Section 3.6 done')
add_heading2(doc, '3.7 时序规则表（TSR）')
add_para(doc, 'TSR 表独立于业务表。应用层通过 CREATE TABLE IF NOT EXISTS 动态创建。')
add_heading3(doc, '3.7.1 TSR 场站数据表（tsr_station）')
add_table(doc, ["字段名", "类型", "说明"], [["station_code", "VARCHAR(10)", "场站编码"], ["station_name", "VARCHAR(100)", "场站名称"]], col_widths=[4, 5, 8])
add_heading3(doc, '3.7.2 TSR 测点数据表（tsr_measure_data）')
add_table(doc, ["字段名", "类型", "说明"], [["cd_code", "VARCHAR(50)", "测点编码"], ["cd_name", "VARCHAR(200)", "测点名称"], ["station_code", "VARCHAR(10)", "场站编码"], ["energy_type", "VARCHAR(10)", "能源类型"], ["measure_code", "VARCHAR(50)", "测点代码"], ["second_code", "VARCHAR(10)", "二级码"], ["extra_code", "VARCHAR(10)", "扩展码"]], col_widths=[4, 5, 8])
add_heading3(doc, '3.7.3 TSR 标准规则列表（tsr_standard_list）')
add_table(doc, ["字段名", "类型", "说明"], [["energy_type", "VARCHAR(10)", "能源类型"], ["module_source", "VARCHAR(50)", "规则来源"], ["second_code", "VARCHAR(10)", "二级码"], ["second_name", "VARCHAR(100)", "二级名称"], ["measure_code", "VARCHAR(50)", "测点代码"], ["measure_name", "VARCHAR(100)", "测点名称"], ["tb_windows", "INTEGER", "突变窗口"], ["ss_windows", "INTEGER", "死值窗口"], ["ss_threshold", "NUMERIC", "死值阈值"], ["yx_range", "VARCHAR(50)", "越限范围"], ["zd_duration", "INTEGER", "终端持续时间"]], col_widths=[4, 5, 8])
add_heading3(doc, '3.7.4 TSR 规则结果表（4张）')
add_table(doc, ["表名", "说明"], [["tsr_import_list_sz", "死值检测"], ["tsr_import_list_tb", "突变检测"], ["tsr_import_list_yx", "越限检测"], ["tsr_import_list_zd", "终端检测"]], col_widths=[6, 10])
print('Section 3.7 done')
add_heading1(doc, '4. 公共审计字段设计')
add_table(doc, ["字段名", "类型", "默认值", "说明"], [["tenant_id", "VARCHAR(50)", "NULL", "租户ID"], ["creator", "VARCHAR(100)", "NULL", "创建人"], ["modifier", "VARCHAR(100)", "NULL", "修改人"], ["create_tm", "TIMESTAMP", "CURRENT_TIMESTAMP", "创建时间"], ["modify_tm", "TIMESTAMP", "CURRENT_TIMESTAMP", "修改时间"], ["if_delete", "CHAR(1)", "0", "逻辑删除 0正常/1删除"]], col_widths=[3, 4, 4, 6])
add_para(doc, '说明：', bold=True)
add_bullet(doc, 'if_delete 实现逻辑删除，DELETE 转换为 UPDATE。')
add_bullet(doc, 'create_tm/modify_tm 记录完整生命周期。')
add_bullet(doc, 'cec_sys_user 表不包含 if_delete 字段。')
print('Section 4 done')
add_heading1(doc, '5. 索引设计')
add_table(doc, ["表名", "索引名", "列", "说明"], [["cec_new_energy_code_dict", "idx_code_dict_tree_query", "type_domain_code,first_class_code,second_class_code,data_category_code", "字典树查询"], ["cec_new_energy_createcode", "idx_createcode_tm", "create_tm DESC", "时间倒序"], ["cec_new_energy_second_class_type_dict", "idx_second_class_type", "type_code,second_class_code", "按类型域查二级类码"], ["cec_new_energy_third_class_dict", "idx_third_class_type_second", "type_code,second_class_code", "按类型域+二级类码"], ["cec_new_energy_measurement_points", "idx_mp_type", "type_code", "按类型域统计"], ["cec_new_energy_measurement_points", "idx_mp_station", "station_code", "按场站统计"], ["cec_new_energy_measurement_points", "idx_mp_second_class", "second_class_code", "按二级类码统计"], ["cec_new_energy_measurement_points", "idx_mp_import_batch", "import_batch_id", "按导入批次"], ["cec_new_energy_measurement_points", "idx_mp_ifdel_crtm", "if_delete,create_tm DESC", "复合过滤排序"], ["cec_new_energy_recent_condition", "idx_recent_condition_tm", "create_tm DESC", "时间倒序"], ["cec_sys_user", "idx_sys_user_username", "username", "按用户名"], ["tsr_measure_data", "idx_tsr_measure_data_station", "station_code", "TSR按场站"], ["tsr_measure_data", "idx_tsr_measure_data_energy", "energy_type", "TSR按类型"], ["tsr_measure_data", "idx_tsr_measure_data_measure", "measure_code", "TSR按测点"], ["tsr_measure_data", "idx_tsr_measure_data_second", "second_code", "TSR按二级码"], ["tsr_measure_data", "idx_tsr_measure_data_energy_second", "energy_type,second_code", "TSR复合"]], col_widths=[5, 7, 10, 8])
print('Section 5 done')
add_heading1(doc, '6. 编码段位存储设计')
add_para(doc, '31位测点编码按预定义段位规则分段，每段对应特定业务含义。')
add_heading2(doc, '6.1 31位编码段位结构')
add_table(doc, ["段位名称", "起始", "长度", "字段名", "说明"], [["场站编码", "1", "4位", "station_code", "场站标识"], ["类型域", "5", "1位", "type_code", "F/G/Y"], ["项目期号", "6", "3位", "project_line_code", "项目期号"], ["前缀号", "9", "1位", "prefix_no", "编码前缀"], ["一级类码", "10", "2位", "first_class_code", "一级分类"], ["二级类码", "12", "3位", "second_class_code", "二级分类"], ["二级扩展码", "15", "4位", "second_ext_code", "二级扩展"], ["三级类码", "19", "3位", "third_class_code", "三级分类"], ["三级扩展码", "22", "4位", "third_ext_code", "三级扩展"], ["数据分类码", "26", "2位", "data_category_code", "数据分类"], ["分隔符", "28", "1位", "占位符", "固定分隔"], ["数据码", "29", "3位", "data_code", "数据项"]], col_widths=[3, 3, 3, 5, 8])
add_para(doc, '总长度：4+1+3+1+2+3+4+3+4+2+1+3 = 31位。')
add_heading2(doc, '6.2 设计说明')
add_bullet(doc, '支持按任意段位分组统计。')
add_bullet(doc, '支持按段位组合条件查询。')
add_bullet(doc, '编码生成仅存完整编码；导入时解析各段位存储。')
print('Section 6 done')
add_heading1(doc, '7. 关键设计说明')
add_heading2(doc, '7.1 主键策略')
add_para(doc, '所有表主键统一用 BIGSERIAL 自增类型。')
add_heading2(doc, '7.2 逻辑删除')
add_para(doc, 'if_delete 标识状态，查询需加 if_delete=0 过滤。')
add_heading2(doc, '7.3 无外键约束')
add_para(doc, '不设物理外键，应用层保证数据完整性。')
add_heading2(doc, '7.4 JSONB 存储')
add_para(doc, '最近筛选条件表使用 JSONB 存储。')
add_heading2(doc, '7.5 编码解析存储')
add_para(doc, '31位编码解析为独立字段存储。')
add_heading2(doc, '7.6 Schema 隔离')
add_para(doc, 'PostgreSQL Schema 实现多租户隔离。')
add_heading2(doc, '7.7 动态建表')
add_para(doc, '映射/修正/TSR 表由应用层动态创建。')
add_heading2(doc, '7.8 审批表分离')
add_para(doc, '审批记录表仅 admin Schema，草稿表存区域 Schema。')
add_heading2(doc, '7.9 TSR 独立性')
add_para(doc, 'TSR 表以 tsr_* 前缀独立命名。')
print('Section 7 done')
add_heading1(doc, '8. SQL规范')
add_heading2(doc, '8.1 命名规则')
add_table(doc, ["对象类型", "命名规则", "示例"], [["表", "小写下划线前缀", "cec_new_energy_code_dict"], ["字段", "小写下划线", "type_domain_code"], ["主键", "表名简写_id", "code_dict_id"], ["索引", "idx_表简写_描述", "idx_code_dict_tree_query"], ["唯一约束", "uk_表简写_字段", "uk_sys_user_username"]], col_widths=[3, 8, 8])
add_heading2(doc, '8.2 查询规范')
add_bullet(doc, '使用参数化查询，禁止字符串拼接。')
add_bullet(doc, 'WHERE 加 if_delete=0 过滤。')
add_bullet(doc, '避免 SELECT*，显式指定字段。')
add_heading2(doc, '8.3 迁移管理')
add_bullet(doc, '命名格式：V{版本号}__{描述}.sql。')
add_bullet(doc, '含前向和回滚脚本。')
add_bullet(doc, '需审查后执行，禁止手动修改。')
print('Section 8 done')
save_doc(doc, '数据库设计文档.docx')
print('Document generation complete!')
